financial_system/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

# from financial_system.api import api
from financial_system.views import site, member, test, shop, balance_informer
from financial_system.views.account import adding_funds, conversion_funds, financial_statement, regular_payment, withdrawal_funds, payment_system, transfer_funds, invoice
from main.views import member as main_member

from api import shop as api_shop
from api import user as api_user


urlpatterns = patterns("",
                       url(r"^$", site.SiteIndex.as_view()),
                       url(r"^profile/$", member.ProfileDetail.as_view(), name="profile"),
                       url(r"^settings/$", site.Settings.as_view(), name="settings"),
                       url(r"^generate_api_token/$", member.TokenView.as_view(), name="generate_api_token"),
                       # url(r"^get_balance_informer/$", member.BalanceInformerView.as_view(), name="get_balance_informer"),
                       url(r"^balance_informer/soc_auth/$", balance_informer.SocAuthView.as_view(), name="balance_informer_soc_auth"),
                       url(r"^balance_informer/soc_auth/(?P<shop_id>\d+)/$", balance_informer.SocAuthView.as_view(), name="balance_informer_soc_auth"),
                       url(r"^balance_informer/login/(?P<shop_id>\d+)/$", balance_informer.Login.as_view(), name="balance_informer_login"),
                       url(r"^balance_informer/logout/(?P<shop_id>\d+)/$", balance_informer.Logout.as_view(), name="balance_informer_logout"),
                       url(r"^balance_informer/(?P<shop_id>\d+)/$", balance_informer.BalanceInformerView.as_view(), name="balance_informer"),


                       url(r"^change_currency/$", site.ChangeCurrency.as_view(), name="change_currency"),
                       url(r"^inform_block/(?P<pk>\d+)/$", site.InformationBlockDetail.as_view(), name="inform_block_detail"),
                       url(r"^registration/$", member.Registration.as_view(), name="registration"),
                       url(r"^registration/complete/$", TemplateView.as_view(template_name="member/registration/registration_complete.html") , name="registration_complete"),
                       url(r"^login/$", member.Login.as_view(), name="login"),
                       url(r"^logout/$", "django.contrib.auth.views.logout", {"next_page": "/"}, name="logout"),
                       url(r"^logout/(?P<next_page>.*)/$", "django.contrib.auth.views.logout", name="logout_next"),
                       url(r"^account/$", financial_statement.FinancialStatement.as_view(), name="account"),
                       url(r"^account_settings/$", member.ProfileSettings.as_view(), name="account_settings"),
                       url(r"^financial_statement/$", financial_statement.FinancialStatement.as_view(), name="financial_statement"),

                       url(r"^regular_payment/list/$", regular_payment.RegularPaymentList.as_view(), name="regular_payment_list"),
                       url(r"^regular_payment/orders/(?P<filter>\w+)/$", regular_payment.RegularPaymentOrderList.as_view(), name="regular_payment_order_list"),
                       url(r"^regular_payment/create/$", regular_payment.RegularPaymentCreate.as_view(), name="regular_payment_create"),
                       url(r"^regular_payment/update/(?P<pk>\d+)/$", regular_payment.RegularPaymentUpdate.as_view(), name="regular_payment_update"),
                       url(r"^regular_payment/order/view/(?P<pk>\d+)/$", regular_payment.RegularPaymentOrderView.as_view(), name="regular_payment_order_view"),

                       url(r"^adding_funds/create/$", adding_funds.AddingFundCreate.as_view(), name="adding_funds_create"),
                       url(r"^adding_funds/create/(?P<payment_sys_code>[^/]+)/$", adding_funds.AddingFundCreate.as_view(), name="adding_funds_create_by_ps"),
                       url(r"^adding_funds/list/$", adding_funds.AddingFundsList.as_view(), name="adding_funds_list"),
                       url(r"^adding_funds/view/(?P<pk>\d+)/$", adding_funds.AddingFundsView.as_view(), name="adding_funds_view"),
                       url(r"^adding_funds/bank_payment_blank_view/(?P<pk>\d+)/$", adding_funds.BankPaymentBlankView.as_view(), name="bank_payment_blank_view"),
                       # url(r"^adding_funds/$", adding_funds.AddingFunds.as_view(), name="adding_funds_create"),
                       # url(r"^adding_funds/(?P<payment_sys_code>[^/]+)/$", adding_funds.AddingFunds.as_view(), name="adding_funds_by_ps"),


                       url(r"^withdrawal_funds/create/$", withdrawal_funds.WithdrawalFundsCreate.as_view(), name="withdrawal_funds_create"),
                       url(r"^withdrawal_funds/create/(?P<payment_system_id>\d+)/$", withdrawal_funds.WithdrawalFundsCreate.as_view(), name="withdrawal_funds_create_by_ps"),
                       url(r"^withdrawal_funds/list/$", withdrawal_funds.WithdrawalFundsList.as_view(), name="withdrawal_funds_list"),
                       url(r"^withdrawal_funds/view/(?P<pk>\d+)/$", withdrawal_funds.WithdrawalFundsView.as_view(), name="withdrawal_funds_view"),


                       url(r"^transfer_funds/create/$", transfer_funds.TransferFundsCreate.as_view(), name="transfer_funds_create"),
                       url(r"^transfer_funds/create/(?P<recipient_id>\d+)/$", transfer_funds.TransferFundsCreate.as_view(), name="transfer_funds_create_by_recipient"),
                       url(r"^transfer_funds/list/(?P<filter>\w+)/$", transfer_funds.TransferFundsList.as_view(), name="transfer_funds_list"),



                       url(r"^transfer_funds/view/(?P<pk>\d+)/$", transfer_funds.TransferFundsView.as_view(), name="transfer_funds_view"),


                       url(r"^invoice/create/$", invoice.InvoiceCreate.as_view(), name="invoice_create"),
                       # url(r"^invoice/create/by_order/(?P<pk>\d+)/$", invoice.InvoiceCreateByOrder.as_view(), name="invoice_create_by_order"),
                       url(r"^invoice/list/(?P<filter>\w+)/$", invoice.InvoiceList.as_view(), name="invoice_list"),
                       url(r"^invoice/list/$", invoice.InvoiceList.as_view(), name="invoice_list"),
                       url(r"^invoice/view/(?P<pk>\d+)/$", invoice.InvoiceView.as_view(), name="invoice_view"),
                       url(r"^invoice/pay/(?P<pk>\d+)/$", invoice.InvoicePay.as_view(), name="invoice_pay"),
                       url(r"^invoice/complete_in_favor_owner/(?P<pk>\d+)/$", invoice.InvoiceCompleteInFavorOwner.as_view(), name="invoice_complete_in_favor_owner"),
                       url(r"^invoice/complete_in_favor_payer/(?P<pk>\d+)/$", invoice.InvoiceCompleteInFavorPayer.as_view(), name="invoice_complete_in_favor_payer"),
                       url(r"^invoice/discussion/send/(?P<pk>\d+)/$", invoice.InvoiceDiscussionView.as_view(), name="invoice_discussion_send"),
                       url(r"^invoice/discussion/(?P<pk>\d+)/$", invoice.InvoiceDiscussionView.as_view(), name="invoice_discussion"),

                       url(r"^conversion_funds/create/$", conversion_funds.ConversionFundsCreate.as_view(), name="conversion_funds_create"),
                       url(r"^conversion_funds/list/$", conversion_funds.ConversionFundsList.as_view(), name="conversion_funds_list"),
                       url(r"^conversion_funds/view/(?P<pk>\d+)/$", conversion_funds.ConversionFundsView.as_view(), name="conversion_funds_view"),

                       url(r"^webmoney_success/$", payment_system.WebmoneySuccess.as_view(), name="webmoney_success"),
                       url(r"^webmoney_result/$", payment_system.WebmoneyResult.as_view(), name="webmoney_result"),
                       url(r"^webmoney_fail/$", payment_system.WebmoneyFail.as_view(), name="webmoney_fail"),
                       url(r"^yandex_result/$", payment_system.YandexResult.as_view(), name="yandex_result"),

                       url(r"^qiwi_result/$", payment_system.QiwiResult.as_view(), name="qiwi_result"),
                       url(r"^qiwi_success/$", payment_system.QiwiSuccess.as_view(), name="qiwi_success"),
                       url(r"^qiwi_fail/$", payment_system.QiwiFail.as_view(), name="qiwi_fail"),

                       url(r"^liqpay_result/$", payment_system.LiqpayResult.as_view(), name="liqpay_result"),
                       url(r"^liqpay_server/$", payment_system.LiqpayServer.as_view(), name="liqpay_server"),

                       url(r"^shop/create/$", shop.ShopCreate.as_view(), name="shop_create"),
                       url(r"^shop/update/(?P<pk>\d+)/$", shop.ShopUpdate.as_view(), name="shop_update"),
                       url(r"^shop/view/(?P<pk>\d+)/$", shop.ShopView.as_view(), name="shop_view"),
                       url(r"^shop/list/$", shop.ShopList.as_view(), name="shop_list"),
                       url(r"^shop/get_perform_payment/$", shop.GetShopPerformPayment.as_view(), name="get_perform_payment"),
                       url(r"^shop/perform_payment/$", shop.ShopPerformPayment.as_view(), name="shop_perform_payment"),

                       url(r"^shop/payment_list/$", shop.ShopPaymentList.as_view(), name="shop_payment_list"),
                       url(r"^shop/payment/view/(?P<pk>\d+)/$", shop.ShopPaymentView.as_view(), name="shop_payment_view"),

                       # url(r"^api/user_balance_list/$", api.UserBalanceList.as_view() , name="api_user_balance_list"),
                       # url(r"^api/user_balance_detail/(?P<pk>\d+)/$", api.UserBalanceDetail.as_view(), name="api_user_balance_detail"),

                       url(r'^new-error-url/$', main_member.LoginSocialBackEndError,  name='new-error-url'),
                       url(r'^new-association-redirect-url/$', main_member.NewAssociation,  name='new-association-redirect-url'),

                       #url(r'^fast_login/$', main_member.FastLogin,  name='fast_login'),

financial_system/forms/shop.py
# --coding: utf-8
from financial_system.fields.account import *
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.formfields import PhoneNumberField


class ShopForm(forms.ModelForm):

    class Meta:
        model = Shop
        exclude = ["user", "profile", "secret_key"]
        widgets = {
            "status": forms.widgets.Select(attrs={"class": "custom-sel", "width": "295", "placeholder": _("Shop status")}),
            "shop_informer": forms.CheckboxInput(attrs={"class": "mic_check"}),
            "informer_language": forms.widgets.Select(
                attrs={"class": "custom-sel", "width": "295", "placeholder": _("Informer default language")}),
        }



class ShopCreateForm(ShopForm):
    pass

class ShopUpdateForm(ShopForm):
    pass


class ShopPaymentForm(forms.Form):
    """reorganize form"""
    shop_id = forms.IntegerField(required=True, widget=forms.TextInput(attrs={},))
    payment_signature = forms.CharField(required=True, widget=forms.TextInput(attrs={}))
    shop_order_id = forms.IntegerField(required=True, widget=forms.TextInput(attrs={}))
    shop_amount = forms.DecimalField(max_digits=9, decimal_places=2, label=_(u"Amount"),
                                validators=[MinValueValidator(Decimal("0.01"))])
    shop_currency = forms.ChoiceField(required=True, label=_("Currency"),
                                      choices=[(c.iso_code, c.name) for c in Currency.objects.filter().exclude(ps_special=1)],
                                      # widget=forms.Select(attrs={"class": "custom-sel all_width"})
    )
    payment_system = forms.ChoiceField(required=True, label=_("Payment system"),
                                       choices=[(ps.sys_code, ps.name) for ps in
                                               PaymentSystem.objects.filter(for_shop_payment=1, active=1)],
                                       # widget=forms.Select(attrs={"class": "custom-sel all_width"})
    )
    phone = PhoneNumberField(required=True, label=_("Phone"))

    ps_currency_type = forms.ChoiceField(required=False, label=_("Payment system currency type"), choices=[("YAR", "YAR", ), ] + WM_TYPE_PURSE_CHOICE + QM_TYPE_PURSE_CHOICE + LP_TYPE_CURRENCY_CHOICE)


class GetShopPaymentForm(ShopPaymentForm):
    pass




class ShopPaymentFailForm(forms.Form):
    errors = forms.CharField(widget=forms.Textarea())


class ShopPaymentSuccessForm(forms.Form):
    payment = forms.CharField(widget=forms.Textarea())

financial_system/templates/shop/get_perform_payment/_form.html
{% load i18n %}
<form method="POST" action="http://{{ request.META.HTTP_HOST }}{% url "shop_perform_payment" %}"  class="shop_perform_payment" id="shop_perform_payment">
    {% for field_obj in form %}
        <div class="row field_{{ field_obj.name }}">
            <div class="col title">
                <label>
                    {{ field_obj.label }}:
                </label>
            </div>
            <div class="col wide">
                <div class="field_{{ field_obj.name }}">
                    {{ field_obj }}
                </div>
            </div>
        </div>
    {% endfor %}
    <div class="row">
        <input type="submit" id="enter" name="send" value="{% trans "Send" %}">
    </div>
</form>

financial_system/templates/shop/get_perform_payment/_view.html
{% spaceless %}
{% load i18n %}
{% load custom_tags %}
{% if request.is_ajax and messages %}
    {% include "messages.html" %}
{% endif %}
<span class="hidden page_path">{{ request.path }}</span>
<div class="wrapper">
    {% include "menu.html" %}
    <div class="cleaner"></div>
    <h1>{% trans "Product pay form" %}</h1>
    {% include "shop/menu.html" %}

    {% blocktrans %}
        This is a sample html page with a form of payment. <br>
        Place example of this form on your site.
    {% endblocktrans %}

    <div class="form_container">
        {% include "shop/get_perform_payment/_view_form.html" %}
    </div>
</div>
{% endspaceless %}

financial_system/templates/shop/get_perform_payment/_view_form.html
{% spaceless %}
{% load i18n %}



<textarea style="height: 500px;">
<html>
<title>YourlStore</title>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script type="text/javascript">
    $(document).ready(function(){
        var WM_currency = {"WMU": "WMU", "WMR": "WMR", "WMZ": "WMZ", "WME": "WME", "WMB": "WMB", "WMX": "WMX"};
        var QM_currency = {"QMR": "QMR", "QME": "QME", "QMK": "QMK", "QMU": "QMU"};
        var LPM_currency = {"LPRUB": "RUB", "LPEUR": "EUR", "LPUSD": "USD", "LPUAH": "UAH"};

        function perform_ps_currency(){
            var ps_currency = false;
            $("#id_ps_currency_type option").remove();
            $(".field_ps_currency_type").hide();

            if ($("#id_payment_system").val()=="WM"){
                ps_currency = WM_currency;
            }
            else if ($("#id_payment_system").val()=="QM"){
                ps_currency = QM_currency;
            }
            else if ($("#id_payment_system").val()=="LPM"){
                ps_currency = LPM_currency;
            }

            if (ps_currency){
                $.each(ps_currency, function(key, value) {
                     $("#id_ps_currency_type")
                         .append($("<option></option>")
                         .attr("value",key)
                         .text(value));
                });
                $(".field_ps_currency_type").show();
            }
            return true;
        }
        perform_ps_currency();

        $("#id_payment_system").on("change", function(){
            perform_ps_currency();

        });
    });

</script>
<body>
	<h1>Your store</h1>
    {% include "shop/get_perform_payment/_form.html" %}
</body>
</html>
</textarea>


<div class="cleaner"></div>
{% endspaceless %}

financial_system/templates/shop/get_perform_payment/view.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Verifair | get perform payment form" %}{% endblock %}
{% block content %}
    {% include "shop/get_perform_payment/_view.html" %}

{% endblock %}